pipeline:
  build:  
    image: devtransition/golang-glide
    secrets: [ secret_string ]
    commands:
      - echo $SECRET_STRING
      - chmod a+x mikungo
      - ./mikungo up
      - ./mikungo test